[package]
name = "turso_sync_engine"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
turso_core = { workspace = true, features = ["conn_raw_api"] }
thiserror = "2.0.12"
tracing = "0.1.41"
serde_json.workspace = true
serde = { workspace = true, features = ["derive"] }
bytes = "1.10.1"
genawaiter = { version = "0.99.1", default-features = false }
http = "1.3.1"
uuid = "1.17.0"

[dev-dependencies]
ctor = "0.4.2"
tempfile = "3.20.0"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
tokio = { version = "1.46.1", features = ["macros", "rt-multi-thread", "test-util"] }
uuid = "1.17.0"
rand = "0.9.2"
rand_chacha = "0.9.0"
turso = { workspace = true, features = ["conn_raw_api"] }
futures = "0.3.31"
