[package]
name = "limbo_ext"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Limbo extensions core"

[features]
core_only = []
static = []

[dependencies]
chrono = "0.4.40"
getrandom = { version = "0.2.15", features = ["js"] }
limbo_macros = { workspace = true }
