name: Run long fuzz tests on Btree

on:
  push:
    paths:
      - 'core/storage/btree.rs'
  pull_request:
    paths:
      - 'core/storage/btree.rs'

jobs:
  run-long-tests:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    timeout-minutes: 0 
    
    steps:
    - uses: actions/checkout@v3
    - uses: useblacksmith/rust-cache@v3
      with:
        prefix-key: "v1-rust" # can be updated if we need to reset caches due to non-trivial change in the dependencies (for example, custom env var were set for single workspace project)
    - name: Set up Python 3.10
      uses: useblacksmith/setup-python@v6
      with:
        python-version: "3.10"
    - name: Build
      run: cargo build --verbose
    - name: Run ignored long tests
      run: cargo test -- --ignored fuzz_long
      env:
        RUST_BACKTRACE: 1
    - name: Run ignored long tests with index
      run: cargo test --features index_experimental -- --ignored fuzz_long
      env:
        RUST_BACKTRACE: 1

  simple-stress-test:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    timeout-minutes: 0
    steps:
    - uses: actions/checkout@v3
    - uses: useblacksmith/rust-cache@v3
      with:
        prefix-key: "v1-rust"
    - name: Set up Python 3.10
      uses: useblacksmith/setup-python@v6
      with:
        python-version: "3.10"
    - name: Build
      run: cargo build --verbose
    - name: Run ignored long tests
      run: cargo run -p limbo_stress -- -t 1 -i 10000 -s
      env:
        RUST_BACKTRACE: 1
